### ISSUE TITLE
Can you make to support other mod like Client Paintings?

### ISSUE THREAD

**Issue by LuckkyZ** [Trikzon/transparent#14]
I am now using Client Paintings for adding new images to my game. So, I want this mod to be officially supported. It will make my city decoration much more beautiful. Thank you so much!

**Comment by Trikzon** [comment]
Transparent already supports the mod Paintings ++ that allows you to create custom paintings.

Transparent *should* work with Client Painting because it *should* use the vanilla painting rendering.

Looking at Client Painting's code, however, it looks like it renders the paintings itself with a "solid" render layer rather than a translucent one. I could theoretically mixin to the mod and change that, but I would rather their code be changed to work better so I don't need to add mod-compatibility code to my mod.

I will try to contact them and/or submit some code to them for it to work with Transparent.

**Comment by Trikzon** [comment]
Correction. I got curious and looked into this (when I probably should have gone to sleep lmao). It is easier for me to change Transparent's code and hook into the render at a later spot and use the texture at that point.

![image](https://github.com/Trikzon/transparent/assets/29845000/d7f98cf1-5766-4e44-b975-1c75bcaa03d5)

The 2x2 painting on the right is added using Client Paintings.

There is a catch to this. You have to add a blank back image to Client Paintings and set that as the back sprite for any transparent paintings (if you want a blank back, which you probably do).

Then you need to put `"back": "clientpaintings:client_paintings/blank"` in the painting's json file.

For example:
```json
{
  "texture": "clientpaintings:client_paintings/galaxy",
  "size": [2, 2],
  "back": "clientpaintings:client_paintings/blank"
}
```

I will upload the updated version tomorrow and will let you know here when it's up.

**Comment by Trikzon** [comment]
https://github.com/Trikzon/transparent/assets/29845000/d0dad563-b5a1-4acf-b5fd-dad58c6e2627
You can download the blank.png here ^

**Comment by LuckkyZ** [comment]
oh wow thank you so much!

**Comment by Trikzon** [comment]
Should work on the latest version (v6.1.1).
Let me know if you have problems
